services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    # networks:
      # - private_net
    volumes:
      - ollama_storage:/root/.ollama
      
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    # networks:
      # - private_net
    volumes:
      - qdrant_storage:/qdrant/storage
      
  postgresDb:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: sample
      POSTGRES_DB: LLM-UIDs
    ports:
      - 5432:5432
    # networks:
      # - private_net
    volumes:
      - postgres_storage:/var/lib/postgresql/data 
      
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgresDb
      
  # n8n:
  #   image: n8nio/n8n
  #   container_name: n8n
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_HOST=localhost
  #     - N8N_PORT=5678
  #     - N8N_PROTOCOL=http
  #     - N8N_USER_MANAGEMENT_DISABLED=true   # 🔑 désactive le login
  #   # networks:
  #     # - public_net
  #     # - private_net
  #   volumes:
  #     - n8n_storage:/home/node/.n8n
  #   depends_on:
  #     - qdrant
  #     - ollama
  #     - postgresDb

volumes:
  qdrant_storage:
    external: true # to use existing volumes
  n8n_storage:
  ollama_storage:
    external: true # to use existing volumes
  postgres_storage:
  
# networks:
  # public_net:
    # driver: bridge
  # private_net:
    # driver: bridge
    # internal: true